server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    url: jdbc:mysql://212.64.104.107:3306/alohajob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

alohajob:
  server:
    version: 0.0.1